import type { Region } from '../types/world.js';

/**
 * The 10 regions of Valdris — the original fantasy continent.
 * Each region has a distinct geographic and economic identity.
 * Base modifiers shape event probability and trade volume.
 */
export const REGIONS: Region[] = [
  {
    id: 'region_aurean_coast',
    name: 'The Aurean Coast',
    type: 'coastal-trade-hub',
    culture: 'trade',
    capital_town_id: 'town_aurea',
    base_risk_modifier: 0.90,
    base_trade_modifier: 1.30,
    description: 'A sweeping natural harbor sheltering the continent\'s largest merchant fleet. Flat coastline, gentle tides, and three river mouths make it the commercial heart of Valdris. Piracy and seasonal storms are the main hazards.',
  },
  {
    id: 'region_valdris_delta',
    name: 'The Valdris Delta',
    type: 'river-delta',
    culture: 'agrarian',
    capital_town_id: 'town_ferrath',
    base_risk_modifier: 0.80,
    base_trade_modifier: 1.10,
    description: 'Fertile floodplains fed by the great Valdris River and its tributaries. The breadbasket of the continent — grain, livestock, and wine flow outward while tools and cloth flow in. Floods and occasional famine are its great risks.',
  },
  {
    id: 'region_ironspine',
    name: 'The Ironspine Mountains',
    type: 'mountain-mining',
    culture: 'frontier',
    capital_town_id: 'town_skarhold',
    base_risk_modifier: 1.25,
    base_trade_modifier: 0.85,
    description: 'Rugged highlands rich in iron, copper, and silver. Towns cling to valleys and switchback roads. Supply costs are high, mine collapses are common, and isolation makes every crisis worse. But the ore that flows from here builds empires.',
  },
  {
    id: 'region_thornwood',
    name: 'The Thornwood',
    type: 'forest-timber',
    culture: 'agrarian',
    capital_town_id: 'town_sylvenmere',
    base_risk_modifier: 1.00,
    base_trade_modifier: 0.95,
    description: 'Dense old-growth forests covering the western highlands. Lumber, charcoal, fur, and medicinal herbs flow from logging camps and trappers\' towns. Slow to develop, prone to fire and floods, but stable once established.',
  },
  {
    id: 'region_dustplains',
    name: 'The Dustplains',
    type: 'steppe-pastoral',
    culture: 'frontier',
    capital_town_id: 'town_yarim',
    base_risk_modifier: 1.35,
    base_trade_modifier: 0.90,
    description: 'Open grasslands and semi-arid steppe stretching across the eastern interior. Horse herds, wool, and leather are its wealth. Raider bands from beyond the plains and brutal droughts define its volatility. Boom-bust cycles are extreme here.',
  },
  {
    id: 'region_caldera_reach',
    name: 'The Caldera Reach',
    type: 'volcanic',
    culture: 'frontier',
    capital_town_id: 'town_ashgate',
    base_risk_modifier: 1.50,
    base_trade_modifier: 0.80,
    description: 'A geologically active zone of volcanic peaks, hot springs, and obsidian flows. Rare minerals, glass crafts, and thermal-heated workshops make it uniquely productive. Eruptions and earthquakes can devastate a town overnight.',
  },
  {
    id: 'region_shattered_isles',
    name: 'The Shattered Isles',
    type: 'island-archipelago',
    culture: 'insular',
    capital_town_id: 'town_corsair_haven',
    base_risk_modifier: 1.20,
    base_trade_modifier: 1.15,
    description: 'A scattered archipelago of deep-water islands with natural harbors. Pearl diving, rare spices, and a thriving transit trade make these islands wealthy — but storms, isolation, and a history of smuggling create a tense relationship with mainland banking.',
  },
  {
    id: 'region_midmark',
    name: 'The Midmark',
    type: 'crossroads',
    culture: 'trade',
    capital_town_id: 'town_midmark_city',
    base_risk_modifier: 0.85,
    base_trade_modifier: 1.25,
    description: 'A central plateau where four great roads converge. Caravans from every corner of Valdris pass through Midmark, making it the most competitive banking territory on the continent. Low geographic risk, but fierce commercial competition.',
  },
  {
    id: 'region_saltmarsh',
    name: 'The Saltmarsh',
    type: 'marshland',
    culture: 'agrarian',
    capital_town_id: 'town_brineholt',
    base_risk_modifier: 1.05,
    base_trade_modifier: 0.90,
    description: 'Wetlands and coastal bogs rich in salt, peat, and medicinal herbs. Its towns are connected by shallow-drafted river barges. Disease risk is the constant threat, and flooding makes each spring tense. But salt is always in demand.',
  },
  {
    id: 'region_greyhaven',
    name: 'The Greyhaven Plateau',
    type: 'highland-plateau',
    culture: 'insular',
    capital_town_id: 'town_greystone',
    base_risk_modifier: 0.95,
    base_trade_modifier: 0.85,
    description: 'Cool, elevated plateau with excellent sheep pastures, stone quarries, and ancient monasteries. Greyhaven folk are deeply conservative — they trust proven institutions only. Slow to extend credit, slow to withdraw it.',
  },
];
