import type { Town } from '../types/world.js';

/**
 * 60 towns across 10 regions (~6 per region).
 * Coordinates are normalized 0–100 for SVG map rendering.
 * Population, wealth, resources, infrastructure, and risk are hand-tuned
 * to reflect each region's geographic and economic identity.
 *
 * Map layout (approximate):
 *   Aurean Coast — west coast (x: 5–20, y: 25–60)
 *   Valdris Delta — south (x: 25–50, y: 70–90)
 *   Ironspine Mountains — north-central (x: 30–55, y: 10–30)
 *   Thornwood — northwest (x: 5–25, y: 10–30)
 *   Dustplains — east (x: 65–95, y: 30–65)
 *   Caldera Reach — far north-east (x: 65–90, y: 5–25)
 *   Shattered Isles — far west coast (x: 0–15, y: 65–90)
 *   Midmark — center (x: 40–65, y: 40–60)
 *   Saltmarsh — south coast (x: 15–40, y: 75–95)
 *   Greyhaven Plateau — south-east highlands (x: 65–90, y: 65–90)
 */
export const TOWNS: Town[] = [

  // ─── AUREAN COAST (coastal-trade-hub) ───────────────────────────────────

  {
    id: 'town_aurea',
    name: 'Aurea',
    region_id: 'region_aurean_coast',
    population: 28000,
    wealth_per_capita: 180,
    economic_output: 0, // computed at runtime
    resources: ['fish', 'spice', 'silk'],
    infrastructure: { roads: 4, port: 5, granary: 3, walls: 3, market: 4 },
    risk_factors: ['piracy_risk', 'storm_risk'],
    is_regional_capital: true,
    x_coord: 12, y_coord: 35,
  },
  {
    id: 'town_portmere',
    name: 'Portmere',
    region_id: 'region_aurean_coast',
    population: 14000,
    wealth_per_capita: 130,
    economic_output: 0,
    resources: ['fish', 'timber'],
    infrastructure: { roads: 3, port: 4, granary: 2, walls: 2, market: 3 },
    risk_factors: ['piracy_risk', 'storm_risk'],
    is_regional_capital: false,
    x_coord: 8, y_coord: 28,
  },
  {
    id: 'town_harwick',
    name: 'Harwick',
    region_id: 'region_aurean_coast',
    population: 9500,
    wealth_per_capita: 110,
    economic_output: 0,
    resources: ['fish', 'salt'],
    infrastructure: { roads: 2, port: 3, granary: 2, walls: 2, market: 2 },
    risk_factors: ['piracy_risk'],
    is_regional_capital: false,
    x_coord: 15, y_coord: 44,
  },
  {
    id: 'town_saltcliff',
    name: 'Saltcliff',
    region_id: 'region_aurean_coast',
    population: 6200,
    wealth_per_capita: 95,
    economic_output: 0,
    resources: ['salt', 'fish'],
    infrastructure: { roads: 2, port: 2, granary: 2, walls: 1, market: 2 },
    risk_factors: ['storm_risk', 'piracy_risk'],
    is_regional_capital: false,
    x_coord: 6, y_coord: 50,
  },
  {
    id: 'town_tidehaven',
    name: 'Tidehaven',
    region_id: 'region_aurean_coast',
    population: 11000,
    wealth_per_capita: 120,
    economic_output: 0,
    resources: ['fish', 'spice'],
    infrastructure: { roads: 3, port: 4, granary: 2, walls: 2, market: 3 },
    risk_factors: ['piracy_risk', 'storm_risk'],
    is_regional_capital: false,
    x_coord: 18, y_coord: 55,
  },
  {
    id: 'town_vestmark',
    name: 'Vestmark',
    region_id: 'region_aurean_coast',
    population: 7800,
    wealth_per_capita: 100,
    economic_output: 0,
    resources: ['fish', 'timber', 'wine'],
    infrastructure: { roads: 3, port: 3, granary: 2, walls: 2, market: 2 },
    risk_factors: ['storm_risk'],
    is_regional_capital: false,
    x_coord: 12, y_coord: 60,
  },

  // ─── VALDRIS DELTA (river-delta) ────────────────────────────────────────

  {
    id: 'town_ferrath',
    name: 'Ferrath',
    region_id: 'region_valdris_delta',
    population: 22000,
    wealth_per_capita: 100,
    economic_output: 0,
    resources: ['grain', 'livestock', 'wine'],
    infrastructure: { roads: 4, port: 3, granary: 4, walls: 3, market: 3 },
    risk_factors: ['flood_prone'],
    is_regional_capital: true,
    x_coord: 38, y_coord: 78,
  },
  {
    id: 'town_millhaven',
    name: 'Millhaven',
    region_id: 'region_valdris_delta',
    population: 12000,
    wealth_per_capita: 85,
    economic_output: 0,
    resources: ['grain', 'wool'],
    infrastructure: { roads: 3, port: 2, granary: 3, walls: 2, market: 2 },
    risk_factors: ['flood_prone'],
    is_regional_capital: false,
    x_coord: 30, y_coord: 82,
  },
  {
    id: 'town_greenford',
    name: 'Greenford',
    region_id: 'region_valdris_delta',
    population: 8500,
    wealth_per_capita: 80,
    economic_output: 0,
    resources: ['grain', 'livestock'],
    infrastructure: { roads: 2, port: 1, granary: 3, walls: 1, market: 2 },
    risk_factors: ['flood_prone', 'plague_risk'],
    is_regional_capital: false,
    x_coord: 44, y_coord: 85,
  },
  {
    id: 'town_longmeadow',
    name: 'Longmeadow',
    region_id: 'region_valdris_delta',
    population: 5500,
    wealth_per_capita: 70,
    economic_output: 0,
    resources: ['grain', 'herbs'],
    infrastructure: { roads: 2, port: 1, granary: 2, walls: 1, market: 1 },
    risk_factors: ['flood_prone'],
    is_regional_capital: false,
    x_coord: 35, y_coord: 88,
  },
  {
    id: 'town_rivenmoor',
    name: 'Rivenmoor',
    region_id: 'region_valdris_delta',
    population: 7200,
    wealth_per_capita: 78,
    economic_output: 0,
    resources: ['fish', 'grain'],
    infrastructure: { roads: 2, port: 2, granary: 3, walls: 2, market: 2 },
    risk_factors: ['flood_prone'],
    is_regional_capital: false,
    x_coord: 48, y_coord: 80,
  },
  {
    id: 'town_harvest_cross',
    name: 'Harvest Cross',
    region_id: 'region_valdris_delta',
    population: 9800,
    wealth_per_capita: 88,
    economic_output: 0,
    resources: ['grain', 'wool', 'livestock'],
    infrastructure: { roads: 3, port: 1, granary: 4, walls: 2, market: 3 },
    risk_factors: ['flood_prone'],
    is_regional_capital: false,
    x_coord: 42, y_coord: 74,
  },

  // ─── IRONSPINE MOUNTAINS (mountain-mining) ───────────────────────────────

  {
    id: 'town_skarhold',
    name: 'Skarhold',
    region_id: 'region_ironspine',
    population: 16000,
    wealth_per_capita: 155,
    economic_output: 0,
    resources: ['iron', 'silver_ore', 'stone'],
    infrastructure: { roads: 3, port: 0, granary: 3, walls: 4, market: 3 },
    risk_factors: ['isolation', 'earthquake_risk'],
    is_regional_capital: true,
    x_coord: 45, y_coord: 18,
  },
  {
    id: 'town_coppergate',
    name: 'Coppergate',
    region_id: 'region_ironspine',
    population: 9000,
    wealth_per_capita: 130,
    economic_output: 0,
    resources: ['copper', 'iron'],
    infrastructure: { roads: 2, port: 0, granary: 2, walls: 3, market: 2 },
    risk_factors: ['isolation', 'earthquake_risk'],
    is_regional_capital: false,
    x_coord: 38, y_coord: 12,
  },
  {
    id: 'town_deepvein',
    name: 'Deepvein',
    region_id: 'region_ironspine',
    population: 5500,
    wealth_per_capita: 145,
    economic_output: 0,
    resources: ['gold_ore', 'silver_ore'],
    infrastructure: { roads: 1, port: 0, granary: 2, walls: 3, market: 2 },
    risk_factors: ['isolation', 'earthquake_risk', 'bandit_raids'],
    is_regional_capital: false,
    x_coord: 52, y_coord: 14,
  },
  {
    id: 'town_anvil_pass',
    name: 'Anvil Pass',
    region_id: 'region_ironspine',
    population: 7000,
    wealth_per_capita: 120,
    economic_output: 0,
    resources: ['iron', 'stone', 'coal'],
    infrastructure: { roads: 3, port: 0, granary: 2, walls: 3, market: 2 },
    risk_factors: ['isolation'],
    is_regional_capital: false,
    x_coord: 34, y_coord: 22,
  },
  {
    id: 'town_forge_hollow',
    name: 'Forge Hollow',
    region_id: 'region_ironspine',
    population: 6200,
    wealth_per_capita: 110,
    economic_output: 0,
    resources: ['iron', 'coal'],
    infrastructure: { roads: 2, port: 0, granary: 2, walls: 2, market: 2 },
    risk_factors: ['isolation', 'earthquake_risk'],
    is_regional_capital: false,
    x_coord: 48, y_coord: 25,
  },
  {
    id: 'town_stonemarsh',
    name: 'Stonemarsh',
    region_id: 'region_ironspine',
    population: 4500,
    wealth_per_capita: 95,
    economic_output: 0,
    resources: ['stone', 'iron'],
    infrastructure: { roads: 2, port: 0, granary: 1, walls: 2, market: 1 },
    risk_factors: ['isolation', 'bandit_raids'],
    is_regional_capital: false,
    x_coord: 42, y_coord: 28,
  },

  // ─── THORNWOOD (forest-timber) ───────────────────────────────────────────

  {
    id: 'town_sylvenmere',
    name: 'Sylvenmere',
    region_id: 'region_thornwood',
    population: 14000,
    wealth_per_capita: 90,
    economic_output: 0,
    resources: ['timber', 'herbs', 'wool'],
    infrastructure: { roads: 3, port: 2, granary: 3, walls: 2, market: 3 },
    risk_factors: ['fire_risk'],
    is_regional_capital: true,
    x_coord: 15, y_coord: 18,
  },
  {
    id: 'town_ashpine',
    name: 'Ashpine',
    region_id: 'region_thornwood',
    population: 7000,
    wealth_per_capita: 75,
    economic_output: 0,
    resources: ['timber', 'coal'],
    infrastructure: { roads: 2, port: 0, granary: 2, walls: 1, market: 2 },
    risk_factors: ['fire_risk', 'flood_prone'],
    is_regional_capital: false,
    x_coord: 8, y_coord: 22,
  },
  {
    id: 'town_barkwood',
    name: 'Barkwood',
    region_id: 'region_thornwood',
    population: 5800,
    wealth_per_capita: 70,
    economic_output: 0,
    resources: ['timber', 'herbs'],
    infrastructure: { roads: 2, port: 0, granary: 2, walls: 1, market: 1 },
    risk_factors: ['fire_risk'],
    is_regional_capital: false,
    x_coord: 20, y_coord: 15,
  },
  {
    id: 'town_furrow',
    name: 'Furrow',
    region_id: 'region_thornwood',
    population: 4500,
    wealth_per_capita: 65,
    economic_output: 0,
    resources: ['timber', 'grain'],
    infrastructure: { roads: 1, port: 0, granary: 2, walls: 1, market: 1 },
    risk_factors: ['fire_risk', 'flood_prone'],
    is_regional_capital: false,
    x_coord: 10, y_coord: 13,
  },
  {
    id: 'town_logrun',
    name: 'Logrun',
    region_id: 'region_thornwood',
    population: 6500,
    wealth_per_capita: 72,
    economic_output: 0,
    resources: ['timber', 'coal', 'herbs'],
    infrastructure: { roads: 2, port: 1, granary: 2, walls: 1, market: 2 },
    risk_factors: ['fire_risk'],
    is_regional_capital: false,
    x_coord: 20, y_coord: 24,
  },
  {
    id: 'town_wyldend',
    name: 'Wyldend',
    region_id: 'region_thornwood',
    population: 3800,
    wealth_per_capita: 60,
    economic_output: 0,
    resources: ['timber', 'herbs'],
    infrastructure: { roads: 1, port: 0, granary: 1, walls: 1, market: 1 },
    risk_factors: ['fire_risk', 'bandit_raids'],
    is_regional_capital: false,
    x_coord: 5, y_coord: 16,
  },

  // ─── DUSTPLAINS (steppe-pastoral) ────────────────────────────────────────

  {
    id: 'town_yarim',
    name: 'Yarim',
    region_id: 'region_dustplains',
    population: 15000,
    wealth_per_capita: 105,
    economic_output: 0,
    resources: ['horses', 'wool', 'livestock'],
    infrastructure: { roads: 3, port: 0, granary: 3, walls: 4, market: 3 },
    risk_factors: ['bandit_raids', 'drought_prone'],
    is_regional_capital: true,
    x_coord: 78, y_coord: 45,
  },
  {
    id: 'town_grassend',
    name: 'Grassend',
    region_id: 'region_dustplains',
    population: 7500,
    wealth_per_capita: 80,
    economic_output: 0,
    resources: ['wool', 'livestock'],
    infrastructure: { roads: 2, port: 0, granary: 2, walls: 3, market: 2 },
    risk_factors: ['bandit_raids', 'drought_prone'],
    is_regional_capital: false,
    x_coord: 88, y_coord: 38,
  },
  {
    id: 'town_dustford',
    name: 'Dustford',
    region_id: 'region_dustplains',
    population: 6000,
    wealth_per_capita: 70,
    economic_output: 0,
    resources: ['horses', 'livestock'],
    infrastructure: { roads: 2, port: 0, granary: 2, walls: 3, market: 2 },
    risk_factors: ['bandit_raids', 'drought_prone'],
    is_regional_capital: false,
    x_coord: 82, y_coord: 55,
  },
  {
    id: 'town_stallion_reach',
    name: 'Stallion Reach',
    region_id: 'region_dustplains',
    population: 5000,
    wealth_per_capita: 90,
    economic_output: 0,
    resources: ['horses'],
    infrastructure: { roads: 2, port: 0, granary: 2, walls: 2, market: 2 },
    risk_factors: ['bandit_raids', 'drought_prone'],
    is_regional_capital: false,
    x_coord: 92, y_coord: 50,
  },
  {
    id: 'town_thornherd',
    name: 'Thornherd',
    region_id: 'region_dustplains',
    population: 4200,
    wealth_per_capita: 65,
    economic_output: 0,
    resources: ['wool', 'livestock', 'grain'],
    infrastructure: { roads: 2, port: 0, granary: 2, walls: 2, market: 1 },
    risk_factors: ['bandit_raids', 'drought_prone'],
    is_regional_capital: false,
    x_coord: 70, y_coord: 58,
  },
  {
    id: 'town_drifter_post',
    name: 'Drifter Post',
    region_id: 'region_dustplains',
    population: 3500,
    wealth_per_capita: 60,
    economic_output: 0,
    resources: ['livestock', 'wool'],
    infrastructure: { roads: 1, port: 0, granary: 1, walls: 2, market: 1 },
    risk_factors: ['bandit_raids', 'drought_prone', 'isolation'],
    is_regional_capital: false,
    x_coord: 95, y_coord: 62,
  },

  // ─── CALDERA REACH (volcanic) ─────────────────────────────────────────────

  {
    id: 'town_ashgate',
    name: 'Ashgate',
    region_id: 'region_caldera_reach',
    population: 12000,
    wealth_per_capita: 195,
    economic_output: 0,
    resources: ['obsidian', 'silver_ore', 'gold_ore'],
    infrastructure: { roads: 2, port: 0, granary: 2, walls: 4, market: 3 },
    risk_factors: ['volcanic_activity', 'earthquake_risk'],
    is_regional_capital: true,
    x_coord: 72, y_coord: 12,
  },
  {
    id: 'town_cinderveil',
    name: 'Cinderveil',
    region_id: 'region_caldera_reach',
    population: 6800,
    wealth_per_capita: 170,
    economic_output: 0,
    resources: ['obsidian', 'copper'],
    infrastructure: { roads: 2, port: 0, granary: 2, walls: 3, market: 2 },
    risk_factors: ['volcanic_activity', 'earthquake_risk'],
    is_regional_capital: false,
    x_coord: 80, y_coord: 8,
  },
  {
    id: 'town_magmahold',
    name: 'Magmahold',
    region_id: 'region_caldera_reach',
    population: 5000,
    wealth_per_capita: 180,
    economic_output: 0,
    resources: ['gold_ore', 'obsidian'],
    infrastructure: { roads: 1, port: 0, granary: 2, walls: 3, market: 2 },
    risk_factors: ['volcanic_activity', 'earthquake_risk', 'isolation'],
    is_regional_capital: false,
    x_coord: 86, y_coord: 15,
  },
  {
    id: 'town_furnace_gate',
    name: 'Furnace Gate',
    region_id: 'region_caldera_reach',
    population: 7500,
    wealth_per_capita: 150,
    economic_output: 0,
    resources: ['copper', 'iron', 'coal'],
    infrastructure: { roads: 2, port: 0, granary: 2, walls: 3, market: 2 },
    risk_factors: ['volcanic_activity', 'earthquake_risk'],
    is_regional_capital: false,
    x_coord: 78, y_coord: 20,
  },
  {
    id: 'town_hearthstone',
    name: 'Hearthstone',
    region_id: 'region_caldera_reach',
    population: 4500,
    wealth_per_capita: 135,
    economic_output: 0,
    resources: ['stone', 'coal'],
    infrastructure: { roads: 2, port: 0, granary: 1, walls: 2, market: 1 },
    risk_factors: ['volcanic_activity'],
    is_regional_capital: false,
    x_coord: 68, y_coord: 18,
  },
  {
    id: 'town_sulfur_cross',
    name: 'Sulfur Cross',
    region_id: 'region_caldera_reach',
    population: 3200,
    wealth_per_capita: 120,
    economic_output: 0,
    resources: ['obsidian'],
    infrastructure: { roads: 1, port: 0, granary: 1, walls: 2, market: 1 },
    risk_factors: ['volcanic_activity', 'earthquake_risk', 'isolation'],
    is_regional_capital: false,
    x_coord: 88, y_coord: 22,
  },

  // ─── SHATTERED ISLES (island-archipelago) ────────────────────────────────

  {
    id: 'town_corsair_haven',
    name: 'Corsair Haven',
    region_id: 'region_shattered_isles',
    population: 13000,
    wealth_per_capita: 160,
    economic_output: 0,
    resources: ['pearls', 'spice', 'fish'],
    infrastructure: { roads: 2, port: 5, granary: 2, walls: 3, market: 3 },
    risk_factors: ['piracy_risk', 'storm_risk'],
    is_regional_capital: true,
    x_coord: 6, y_coord: 72,
  },
  {
    id: 'town_pearl_rock',
    name: 'Pearl Rock',
    region_id: 'region_shattered_isles',
    population: 5500,
    wealth_per_capita: 140,
    economic_output: 0,
    resources: ['pearls', 'fish'],
    infrastructure: { roads: 1, port: 4, granary: 1, walls: 2, market: 2 },
    risk_factors: ['storm_risk', 'isolation'],
    is_regional_capital: false,
    x_coord: 2, y_coord: 80,
  },
  {
    id: 'town_spice_harbor',
    name: 'Spice Harbor',
    region_id: 'region_shattered_isles',
    population: 7800,
    wealth_per_capita: 155,
    economic_output: 0,
    resources: ['spice', 'fish'],
    infrastructure: { roads: 1, port: 4, granary: 2, walls: 2, market: 3 },
    risk_factors: ['piracy_risk', 'storm_risk'],
    is_regional_capital: false,
    x_coord: 10, y_coord: 80,
  },
  {
    id: 'town_wave_break',
    name: 'Wave Break',
    region_id: 'region_shattered_isles',
    population: 4200,
    wealth_per_capita: 120,
    economic_output: 0,
    resources: ['fish', 'salt'],
    infrastructure: { roads: 1, port: 3, granary: 1, walls: 2, market: 1 },
    risk_factors: ['storm_risk', 'isolation'],
    is_regional_capital: false,
    x_coord: 4, y_coord: 87,
  },
  {
    id: 'town_shallowmere',
    name: 'Shallowmere',
    region_id: 'region_shattered_isles',
    population: 3800,
    wealth_per_capita: 110,
    economic_output: 0,
    resources: ['fish', 'pearls'],
    infrastructure: { roads: 1, port: 3, granary: 1, walls: 1, market: 2 },
    risk_factors: ['storm_risk', 'piracy_risk'],
    is_regional_capital: false,
    x_coord: 12, y_coord: 86,
  },
  {
    id: 'town_deepchannel',
    name: 'Deepchannel',
    region_id: 'region_shattered_isles',
    population: 6000,
    wealth_per_capita: 130,
    economic_output: 0,
    resources: ['fish', 'spice'],
    infrastructure: { roads: 1, port: 4, granary: 2, walls: 2, market: 2 },
    risk_factors: ['piracy_risk', 'storm_risk'],
    is_regional_capital: false,
    x_coord: 8, y_coord: 66,
  },

  // ─── MIDMARK (crossroads) ─────────────────────────────────────────────────

  {
    id: 'town_midmark_city',
    name: 'Midmark City',
    region_id: 'region_midmark',
    population: 32000,
    wealth_per_capita: 200,
    economic_output: 0,
    resources: ['grain', 'wool', 'spice', 'silk'],
    infrastructure: { roads: 5, port: 0, granary: 4, walls: 3, market: 5 },
    risk_factors: ['political_instability'],
    is_regional_capital: true,
    x_coord: 52, y_coord: 48,
  },
  {
    id: 'town_waygate',
    name: 'Waygate',
    region_id: 'region_midmark',
    population: 14000,
    wealth_per_capita: 160,
    economic_output: 0,
    resources: ['grain', 'spice'],
    infrastructure: { roads: 4, port: 0, granary: 3, walls: 2, market: 4 },
    risk_factors: ['political_instability'],
    is_regional_capital: false,
    x_coord: 60, y_coord: 42,
  },
  {
    id: 'town_crosshaven',
    name: 'Crosshaven',
    region_id: 'region_midmark',
    population: 11000,
    wealth_per_capita: 145,
    economic_output: 0,
    resources: ['wool', 'silk'],
    infrastructure: { roads: 4, port: 0, granary: 3, walls: 2, market: 3 },
    risk_factors: [],
    is_regional_capital: false,
    x_coord: 45, y_coord: 52,
  },
  {
    id: 'town_junction',
    name: 'Junction',
    region_id: 'region_midmark',
    population: 8500,
    wealth_per_capita: 130,
    economic_output: 0,
    resources: ['grain', 'iron'],
    infrastructure: { roads: 4, port: 0, granary: 3, walls: 2, market: 3 },
    risk_factors: [],
    is_regional_capital: false,
    x_coord: 55, y_coord: 55,
  },
  {
    id: 'town_tradefort',
    name: 'Tradefort',
    region_id: 'region_midmark',
    population: 10000,
    wealth_per_capita: 140,
    economic_output: 0,
    resources: ['grain', 'wine', 'horses'],
    infrastructure: { roads: 3, port: 0, granary: 3, walls: 3, market: 4 },
    risk_factors: ['political_instability'],
    is_regional_capital: false,
    x_coord: 62, y_coord: 53,
  },
  {
    id: 'town_halting_green',
    name: 'Halting Green',
    region_id: 'region_midmark',
    population: 7000,
    wealth_per_capita: 115,
    economic_output: 0,
    resources: ['grain', 'wool'],
    infrastructure: { roads: 3, port: 0, granary: 3, walls: 2, market: 2 },
    risk_factors: [],
    is_regional_capital: false,
    x_coord: 47, y_coord: 44,
  },

  // ─── SALTMARSH (marshland) ────────────────────────────────────────────────

  {
    id: 'town_brineholt',
    name: 'Brineholt',
    region_id: 'region_saltmarsh',
    population: 12000,
    wealth_per_capita: 85,
    economic_output: 0,
    resources: ['salt', 'peat', 'fish'],
    infrastructure: { roads: 2, port: 3, granary: 3, walls: 2, market: 3 },
    risk_factors: ['plague_risk', 'flood_prone'],
    is_regional_capital: true,
    x_coord: 28, y_coord: 88,
  },
  {
    id: 'town_bogside',
    name: 'Bogside',
    region_id: 'region_saltmarsh',
    population: 5500,
    wealth_per_capita: 65,
    economic_output: 0,
    resources: ['peat', 'herbs'],
    infrastructure: { roads: 1, port: 1, granary: 2, walls: 1, market: 1 },
    risk_factors: ['plague_risk', 'flood_prone'],
    is_regional_capital: false,
    x_coord: 20, y_coord: 90,
  },
  {
    id: 'town_salt_landing',
    name: 'Salt Landing',
    region_id: 'region_saltmarsh',
    population: 7200,
    wealth_per_capita: 78,
    economic_output: 0,
    resources: ['salt', 'fish'],
    infrastructure: { roads: 1, port: 3, granary: 2, walls: 2, market: 2 },
    risk_factors: ['flood_prone'],
    is_regional_capital: false,
    x_coord: 22, y_coord: 82,
  },
  {
    id: 'town_reedhaven',
    name: 'Reedhaven',
    region_id: 'region_saltmarsh',
    population: 4500,
    wealth_per_capita: 60,
    economic_output: 0,
    resources: ['peat', 'herbs', 'salt'],
    infrastructure: { roads: 1, port: 2, granary: 2, walls: 1, market: 1 },
    risk_factors: ['plague_risk', 'flood_prone'],
    is_regional_capital: false,
    x_coord: 32, y_coord: 92,
  },
  {
    id: 'town_mudwater',
    name: 'Mudwater',
    region_id: 'region_saltmarsh',
    population: 3800,
    wealth_per_capita: 55,
    economic_output: 0,
    resources: ['fish', 'peat'],
    infrastructure: { roads: 1, port: 1, granary: 1, walls: 1, market: 1 },
    risk_factors: ['plague_risk', 'flood_prone'],
    is_regional_capital: false,
    x_coord: 38, y_coord: 94,
  },
  {
    id: 'town_brack',
    name: 'Brack',
    region_id: 'region_saltmarsh',
    population: 4800,
    wealth_per_capita: 70,
    economic_output: 0,
    resources: ['salt', 'herbs'],
    infrastructure: { roads: 2, port: 2, granary: 2, walls: 1, market: 2 },
    risk_factors: ['plague_risk', 'flood_prone'],
    is_regional_capital: false,
    x_coord: 16, y_coord: 85,
  },

  // ─── GREYHAVEN PLATEAU (highland-plateau) ────────────────────────────────

  {
    id: 'town_greystone',
    name: 'Greystone',
    region_id: 'region_greyhaven',
    population: 18000,
    wealth_per_capita: 115,
    economic_output: 0,
    resources: ['stone', 'wool', 'grain'],
    infrastructure: { roads: 3, port: 0, granary: 4, walls: 4, market: 3 },
    risk_factors: ['isolation'],
    is_regional_capital: true,
    x_coord: 76, y_coord: 75,
  },
  {
    id: 'town_shepherd_vale',
    name: 'Shepherd Vale',
    region_id: 'region_greyhaven',
    population: 8500,
    wealth_per_capita: 90,
    economic_output: 0,
    resources: ['wool', 'livestock'],
    infrastructure: { roads: 2, port: 0, granary: 3, walls: 2, market: 2 },
    risk_factors: ['isolation'],
    is_regional_capital: false,
    x_coord: 85, y_coord: 70,
  },
  {
    id: 'town_quarry_ridge',
    name: 'Quarry Ridge',
    region_id: 'region_greyhaven',
    population: 7000,
    wealth_per_capita: 100,
    economic_output: 0,
    resources: ['stone', 'iron'],
    infrastructure: { roads: 2, port: 0, granary: 2, walls: 3, market: 2 },
    risk_factors: ['isolation'],
    is_regional_capital: false,
    x_coord: 92, y_coord: 78,
  },
  {
    id: 'town_coldvale',
    name: 'Coldvale',
    region_id: 'region_greyhaven',
    population: 6200,
    wealth_per_capita: 88,
    economic_output: 0,
    resources: ['wool', 'grain'],
    infrastructure: { roads: 2, port: 0, granary: 3, walls: 2, market: 2 },
    risk_factors: ['isolation'],
    is_regional_capital: false,
    x_coord: 72, y_coord: 82,
  },
  {
    id: 'town_monastic_hill',
    name: 'Monastic Hill',
    region_id: 'region_greyhaven',
    population: 5000,
    wealth_per_capita: 95,
    economic_output: 0,
    resources: ['herbs', 'stone'],
    infrastructure: { roads: 2, port: 0, granary: 3, walls: 3, market: 2 },
    risk_factors: ['isolation'],
    is_regional_capital: false,
    x_coord: 80, y_coord: 85,
  },
  {
    id: 'town_highpass',
    name: 'Highpass',
    region_id: 'region_greyhaven',
    population: 4500,
    wealth_per_capita: 82,
    economic_output: 0,
    resources: ['stone', 'wool'],
    infrastructure: { roads: 3, port: 0, granary: 2, walls: 3, market: 2 },
    risk_factors: ['isolation'],
    is_regional_capital: false,
    x_coord: 88, y_coord: 88,
  },
];
