import { DEPOSIT_GENERATION_RATE } from '../constants/game.js';
import { DEPOSIT_RATE_EXPONENT, DEPOSIT_REPUTATION_EXPONENT } from '../constants/economics.js';

export interface BankPresence {
  player_id: string;
  offered_rate: number;    // Annual rate, e.g. 0.05 = 5%
  reputation: number;      // 0–100
}

export interface DepositFlowResult {
  player_id: string;
  new_deposits: number;
}

/**
 * Total new deposits generated by a town this tick.
 * Roughly 0.1% of economic output flows as new citizen savings per tick.
 */
export function calcTotalNewDeposits(townEconomicOutput: number): number {
  return townEconomicOutput * DEPOSIT_GENERATION_RATE;
}

/**
 * Attraction score for a single bank in a town.
 * Rate-sensitivity is higher than reputation sensitivity.
 */
export function calcAttractionScore(bank: BankPresence, maxRateInTown: number): number {
  if (maxRateInTown <= 0) return 0;
  const rateComponent = Math.pow(bank.offered_rate / maxRateInTown, DEPOSIT_RATE_EXPONENT);
  const repComponent = Math.pow(bank.reputation / 100, DEPOSIT_REPUTATION_EXPONENT);
  return rateComponent * repComponent;
}

/**
 * Distribute new deposits among all licensed banks in a town proportionally
 * by their attraction score.
 */
export function calcDepositDistribution(
  townEconomicOutput: number,
  banks: BankPresence[],
): DepositFlowResult[] {
  if (banks.length === 0) return [];

  const totalNew = calcTotalNewDeposits(townEconomicOutput);
  const maxRate = Math.max(...banks.map(b => b.offered_rate), 0.001);

  const scores = banks.map(b => ({
    player_id: b.player_id,
    score: calcAttractionScore(b, maxRate),
  }));

  const totalScore = scores.reduce((acc, s) => acc + s.score, 0);
  if (totalScore <= 0) {
    // No one is offering attractive rates — distribute evenly
    const even = totalNew / banks.length;
    return banks.map(b => ({ player_id: b.player_id, new_deposits: even }));
  }

  return scores.map(s => ({
    player_id: s.player_id,
    new_deposits: totalNew * (s.score / totalScore),
  }));
}

/**
 * Interest accrued on deposits this tick.
 * annualRate / TICKS_PER_YEAR = per-tick rate
 */
export function calcDepositInterestPerTick(balance: number, annualRate: number, ticksPerYear = 360): number {
  return balance * (annualRate / ticksPerYear);
}

/**
 * Deposit withdrawal pressure: if reserve ratio is below minimum,
 * citizens sense instability and may start withdrawing.
 * Returns fraction of deposits withdrawn this tick (0–1).
 */
export function calcWithdrawalPressure(
  reserveRatio: number,
  minReserveRatio: number,
  reputation: number,
): number {
  if (reserveRatio >= minReserveRatio) return 0;
  // Below minimum: withdrawal pressure scales with how far below we are
  const deficit = (minReserveRatio - reserveRatio) / minReserveRatio;
  // Also modulated by reputation — good reputation buys time
  const reputationBuffer = (reputation / 100) * 0.5;
  return Math.max(0, deficit * 0.05 - reputationBuffer * 0.01);
}
